[package]
name = "tinyprof"
description = "Tiny realtime frame profiler, well used with tinyecs"
repository = "https://github.com/not-fl3/tinyprof.git"
keywords = ["profiler"]
authors = ["not.fl3@gmail.com"]
license = "MIT"
version = "0.0.1"


[dependencies]
time = "0.1"
lazy_static = "0.1.15"
